SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

MENU_OFFSET = 100

STATE_START = "start"
STATE_GAME = "game"
STATE_END = "end"

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8 
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SCORE_VALUE = 10

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3
PLAYER_BOMB_COOLDOWN = 5
PLAYER_DAMAGE_COOLDOWN = 1
PLAYER_MAX_LIVES = 3

SHOT_RADIUS = 5
BOMB_RADIUS = 10

